---
  language: go
  sudo: false
  branches:
  only:
  - master
  - develop
  notifications:
    email: true
  pushover:
    api_key:
      secure: Xk7hCu2tQ4uAzB/v6hER3MNcZSMy4kusgt6suTM++fAAHxhPWJAQp9T9dX6aBHjhag+I1wPoqg71O5Nzi7JCz3gzUgMbGSPk2t1LFn4iZJh8jXfPzKYSLG9L4XRrrVTidXPIFT5FXQ9R66vy/x37f0mFtD8iWyh6dDn6E2w4cZB2dYvxbcQuB0Yot4Zcrj+HCgeHM01CYQKDSGVAmXOuwcz3zohrpEVNJIFjeNIETWDa8Rm8/sfLtiUZVMgXadXF5UX6/2ExndQaHt0oailxKgZ7v+Wly3LKm1U4QKMZ33rwfZk1uyLfMPqsYIKj41G1iuazsg0eFa/agR976xDvIK2vC7Hzr3RwdlXQW5vZWv4+4EwayZwZyCxJfb0qZ2a+obZ9vYXvN9IkhWvv8RGcZWvF6hfic4jKFnLN2cSYvVw1CfdlwCosb5ghwFHlC1PG0DlPs7p9z8FBNME1tmGLk4HoTk2b5fDwRQIXTylmbBZIhn12DSXi0g7BNDDIgErK4/WnkF12yngauSHmgGQPPLzPZB4LlsTSUr8yukNB2PHgGv1a2oahXV5TU5TPwmM65y6HZKqvClIlYcpozCO3NnbNmdl/P/yPHJTvhHraG1/lOnvTeqNQkBzbml5Hx8E57WTRbR5ETvc1FgtEvUQdf0jtH8wzuCBhv26OKtxqePE=
    users:
      secure: A2PXof51gv0D3h5leAhM/xptYbxB9Z0AJ4O6b78a/3UGqDzuiCCeIFPFXNfyWyCwBImLOUgfakk2YVFiRM5OFN7OC/gm1YpTrWNRCUWvyoDreskUtrx07TH1ZF7bUB0DsdbTrPpTP09ApHvjhE7aUUWkJLOROUIOJBj6YIpihae3/cLpnixKC1vVevm7fX7MV3WI8mVcNQ8C7k5/VROrjU7djgkyXmZkLT9ipK2aeXHsjUVzANFMKNQchqcZsqY6rhyb2FgDivYFL+N16qyr5b078Jr1Ztr1T437s0gmBZYFdxvZG3rKHu+M5MlU+4tjTjrPM5W+YSDsdMc22jsc6RDM0qdXAXHSWnwDs2l0ZXGIormyk1/y2s4eHq1jnj5NtnsV5JAwSaOUzgp9vL7zzhC8rQZDK62BVcC8ac6XTORdzzCyiIzJ0VTN8bfWJu8zvvM/sdBiTWfxYVq4ti3zjCEbnS6gDg6e1frReyM5pTc6sC9nm0d18VcX7GjuDfhd/Pd16uveiuwphecovfe6f8sG/23Cx4AYoxZwpT5ZWYORyUSVXqQjPKNGQ2GX4tKDwroW0UWSGaCji/8TgwguWDCf5avEExcI8KRE8lFmINCspcEPqVI+0757/laGRTHcYEi/xY6e91HB3TY/0dxTmiASVXr8Tz2VMIX/XRguu6k=
  go:
    - 1.8.x
    - 1.9.x
    - 1.10.x
    - master
    - tip
  env:
    global:
      - GO15VENDOREXPERIMENT=1
  install:
    - go get github.com/golang/lint/golint
  script:
    - go build -v
    - go vet $(go list ./... | grep -v vendor)
    - test -z "$(golint ./... | grep -v vendor | tee /dev/stderr)"
    - test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"
    - go test $(go list ./... | grep -v vendor)
